USE TRABAJADORES
GO

CREATE TABLE EMPLEADO (
NUMERO_DE_EMPLEADO INT NOT NULL IDENTITY,
NOMBRE VARCHAR (50) NOT NULL,
FECHA_DE_NACIMIENTO DATE NOT NULL,
RFC VARCHAR (13) NOT NULL,
NOMBRE_DE_CENTRO VARCHAR (20) NOT NULL,
DESCRIPCION_DEL_PUESTO VARCHAR NOT NULL,
[¿ES DIRECTIVO?] VARCHAR (2)NOT NULL,


)
CREATE TABLE EMPLEADO (
NUMERO_DE_EMPLEADO INT NOT NULL IDENTITY,
NOMBRE VARCHAR (50) NOT NULL,
FECHA_DE_NACIMIENTO DATE NOT NULL,
RFC VARCHAR (13) NOT NULL,
NOMBRE_DE_CENTRO VARCHAR (20) NOT NULL,
DESCRIPCION_DEL_PUESTO VARCHAR (20) NOT NULL,
[¿ES DIRECTIVO?] VARCHAR (2)NOT NULL,


)